# 上下文初始化加载
info:
  name: Eureka server
  contact: Top音乐计划
  
management:
  security:
    enabled: false
    
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev

server:
  port: 8761
eureka:
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉取信息
    fetchRegistry: false
    # eureka server地址
    serviceUrl:
      defaultZone: ${eureka_serviceUrl:http://master:8761/eureka/}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
  instance:
    hostname: ${INSTANCE_HOSTNAME}


---
spring:
  profiles: prod
  cloud:
    client:
      hostname: ${HOSTNAME}

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka_serviceUrl}

  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
    # 服务剔除任务执行周期
    evictionIntervalTimerInMs: 60000
    # 服务端缓存最长时间
    responseCacheUpdateIntervalMs: 30000
  instance:
    hostname: ${INSTANCE_HOSTNAME}